<?php
/**
 * Created by PhpStorm.
 * User: Mateo
 * Date: 08-Dec-17
 * Time: 17:32
 */
?>

<div id="fullsize" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <div class="controls">
            <div class="control" onclick="showNext('prev')">
                <i class="fa fa-angle-double-left"></i>
            </div>
            <div class="img_full" id="img_identifier">
                <img src="#" id="full_sized_image">
            </div>
            <div class="control" onclick="showNext('next')">
                <i class="fa fa-angle-double-right"></i>
            </div>
        </div>

    </div>

</div>
