<?php

?>
<br><br>
<div id="space" style="visibility: hidden"></div>
<footer id="footer" class="container-fluid">
    <div class="row d-flex flex-row align-items-center">
        <div class="col-sm-12 col-md-5 col-lg-5 align-content-center">
            <span>GROUP 1700 - KOFI TU GO <br>&copy;All Rights Reserved; Web & Mobile II</span>
        </div>
        <div class="col-sm-12 col-md-2 col-lg-4 justify-content-center">
            <a class="align-self-center" href="<?php echo getRootPath($pageName).'pages/references.html'?>">
                References
            </a>
        </div>

        <div class="col-sm-12 col-md-5 col-lg-3 justify-content-center">
                <span>
                    Group Members: Mateo Lucic, Teo Surkovic, Marino Bjelopera, Klara Lucianovic
                </span>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="<?php echo getRootPath($pageName) . 'scripts/bootstrap.js' ?>"></script>
<script src="<?php echo getRootPath($pageName) . 'scripts/script.js' ?>"></script>

</body>
</html>